export const defaultLang = [
	{ to: "ab", name: "Abkhazian" },
	{ to: "aa", name: "Afar" },
	{ to: "af", name: "Afrikaans" },
	{ to: "ak", name: "Akan" },
	{ to: "sq", name: "Albanian" },
	{ to: "am", name: "Amharic" },
	{ to: "ar", name: "Arabic" },
	{ to: "an", name: "Aragonese" },
	{ to: "hy", name: "Armenian" },
	{ to: "as", name: "Assamese" },
	{ to: "av", name: "Avaric" },
	{ to: "ae", name: "Avestan" },
	{ to: "ay", name: "Aymara" },
	{ to: "az", name: "Azerbaijani" },
	{ to: "bm", name: "Bambara" },
	{ to: "ba", name: "Bashkir" },
	{ to: "eu", name: "Basque" },
	{ to: "be", name: "Belarusian" },
	{ to: "bn", name: "Bengali" },
	{ to: "bh", name: "Bihari languages" },
	{ to: "bi", name: "Bislama" },
	{ to: "bs", name: "Bosnian" },
	{ to: "br", name: "Breton" },
	{ to: "bg", name: "Bulgarian" },
	{ to: "my", name: "Burmese" },
	{ to: "ca", name: "Catalan, Valencian" },
	{ to: "km", name: "Central Khmer" },
	{ to: "ch", name: "Chamorro" },
	{ to: "ce", name: "Chechen" },
	{ to: "ny", name: "Chichewa, Chewa, Nyanja" },
	{ to: "zh", name: "Chinese" },
	{ to: "cu", name: "Church Slavonic, Old Bulgarian, Old Church Slavonic" },
	{ to: "cv", name: "Chuvash" },
	{ to: "kw", name: "Cornish" },
	{ to: "co", name: "Corsican" },
	{ to: "cr", name: "Cree" },
	{ to: "hr", name: "Croatian" },
	{ to: "cs", name: "Czech" },
	{ to: "da", name: "Danish" },
	{ to: "dv", name: "Divehi, Dhivehi, Maldivian" },
	{ to: "nl", name: "Dutch, Flemish" },
	{ to: "dz", name: "Dzongkha" },
	{ to: "en", name: "English" },
	{ to: "eo", name: "Esperanto" },
	{ to: "et", name: "Estonian" },
	{ to: "ee", name: "Ewe" },
	{ to: "fo", name: "Faroese" },
	{ to: "fj", name: "Fijian" },
	{ to: "fi", name: "Finnish" },
	{ to: "fr", name: "French" },
	{ to: "ff", name: "Fulah" },
	{ to: "gd", name: "Gaelic, Scottish Gaelic" },
	{ to: "gl", name: "Galician" },
	{ to: "lg", name: "Ganda" },
	{ to: "ka", name: "Georgian" },
	{ to: "de", name: "German" },
	{ to: "ki", name: "Gikuyu, Kikuyu" },
	{ to: "el", name: "Greek (Modern)" },
	{ to: "kl", name: "Greenlandic, Kalaallisut" },
	{ to: "gn", name: "Guarani" },
	{ to: "gu", name: "Gujarati" },
	{ to: "ht", name: "Haitian, Haitian Creole" },
	{ to: "ha", name: "Hausa" },
	{ to: "he", name: "Hebrew" },
	{ to: "hz", name: "Herero" },
	{ to: "hi", name: "Hindi" },
	{ to: "ho", name: "Hiri Motu" },
	{ to: "hu", name: "Hungarian" },
	{ to: "is", name: "Icelandic" },
	{ to: "io", name: "Ido" },
	{ to: "ig", name: "Igbo" },
	{ to: "id", name: "Indonesian" },
	{ to: "ie", name: "Interlingue" },
	{ to: "iu", name: "Inuktitut" },
	{ to: "ik", name: "Inupiaq" },
	{ to: "ga", name: "Irish" },
	{ to: "it", name: "Italian" },
	{ to: "ja", name: "Japanese" },
	{ to: "jv", name: "Javanese" },
	{ to: "kn", name: "Kannada" },
	{ to: "kr", name: "Kanuri" },
	{ to: "ks", name: "Kashmiri" },
	{ to: "kk", name: "Kazakh" },
	{ to: "rw", name: "Kinyarwanda" },
	{ to: "kv", name: "Komi" },
	{ to: "kg", name: "Kongo" },
	{ to: "ko", name: "Korean" },
	{ to: "kj", name: "Kwanyama, Kuanyama" },
	{ to: "ku", name: "Kurdish" },
	{ to: "ky", name: "Kyrgyz" },
	{ to: "lo", name: "Lao" },
	{ to: "la", name: "Latin" },
	{ to: "lv", name: "Latvian" },
	{ to: "lb", name: "Letzeburgesch, Luxembourgish" },
	{ to: "li", name: "Limburgish, Limburgan, Limburger" },
	{ to: "ln", name: "Lingala" },
	{ to: "lt", name: "Lithuanian" },
	{ to: "lu", name: "Luba-Katanga" },
	{ to: "mk", name: "Macedonian" },
	{ to: "mg", name: "Malagasy" },
	{ to: "ms", name: "Malay" },
	{ to: "ml", name: "Malayalam" },
	{ to: "mt", name: "Maltese" },
	{ to: "gv", name: "Manx" },
	{ to: "mi", name: "Maori" },
	{ to: "mr", name: "Marathi" },
	{ to: "mh", name: "Marshallese" },
	{ to: "ro", name: "Moldovan, Moldavian, Romanian" },
	{ to: "mn", name: "Mongolian" },
	{ to: "na", name: "Nauru" },
	{ to: "nv", name: "Navajo, Navaho" },
	{ to: "nd", name: "Northern Ndebele" },
	{ to: "ng", name: "Ndonga" },
	{ to: "ne", name: "Nepali" },
	{ to: "se", name: "Northern Sami" },
	{ to: "no", name: "Norwegian" },
	{ to: "nb", name: "Norwegian Bokmål" },
	{ to: "nn", name: "Norwegian Nynorsk" },
	{ to: "ii", name: "Nuosu, Sichuan Yi" },
	{ to: "oc", name: "Occitan (post 1500)" },
	{ to: "oj", name: "Ojibwa" },
	{ to: "or", name: "Oriya" },
	{ to: "om", name: "Oromo" },
	{ to: "os", name: "Ossetian, Ossetic" },
	{ to: "pi", name: "Pali" },
	{ to: "pa", name: "Panjabi, Punjabi" },
	{ to: "ps", name: "Pashto, Pushto" },
	{ to: "fa", name: "Persian" },
	{ to: "pl", name: "Polish" },
	{ to: "pt", name: "Portuguese" },
	{ to: "qu", name: "Quechua" },
	{ to: "rm", name: "Romansh" },
	{ to: "rn", name: "Rundi" },
	{ to: "ru", name: "Russian" },
	{ to: "sm", name: "Samoan" },
	{ to: "sg", name: "Sango" },
	{ to: "sa", name: "Sanskrit" },
	{ to: "sc", name: "Sardinian" },
	{ to: "sr", name: "Serbian" },
	{ to: "sn", name: "Shona" },
	{ to: "sd", name: "Sindhi" },
	{ to: "si", name: "Sinhala, Sinhalese" },
	{ to: "sk", name: "Slovak" },
	{ to: "sl", name: "Slovenian" },
	{ to: "so", name: "Somali" },
	{ to: "st", name: "Sotho, Southern" },
	{ to: "nr", name: "South Ndebele" },
	{ to: "es", name: "Spanish" },
	{ to: "su", name: "Sundanese" },
	{ to: "sw", name: "Swahili" },
	{ to: "ss", name: "Swati" },
	{ to: "sv", name: "Swedish" },
	{ to: "tl", name: "Tagalog" },
	{ to: "ty", name: "Tahitian" },
	{ to: "tg", name: "Tajik" },
	{ to: "ta", name: "Tamil" },
	{ to: "tt", name: "Tatar" },
	{ to: "te", name: "Telugu" },
	{ to: "th", name: "Thai" },
	{ to: "bo", name: "Tibetan" },
	{ to: "ti", name: "Tigrinya" },
	{ to: "to", name: "Tonga (Tonga Islands)" },
	{ to: "ts", name: "Tsonga" },
	{ to: "tn", name: "Tswana" },
	{ to: "tr", name: "Turkish" },
	{ to: "tk", name: "Turkmen" },
	{ to: "tw", name: "Twi" },
	{ to: "ug", name: "Uighur, Uyghur" },
	{ to: "uk", name: "Ukrainian" },
	{ to: "ur", name: "Urdu" },
	{ to: "uz", name: "Uzbek" },
	{ to: "ve", name: "Venda" },
	{ to: "vi", name: "Vietnamese" },
	{ to: "vo", name: "Volap_k" },
	{ to: "wa", name: "Walloon" },
	{ to: "cy", name: "Welsh" },
	{ to: "fy", name: "Western Frisian" },
	{ to: "wo", name: "Wolof" },
	{ to: "xh", name: "Xhosa" },
	{ to: "yi", name: "Yiddish" },
	{ to: "yo", name: "Yoruba" },
	{ to: "za", name: "Zhuang, Chuang" },
	{ to: "zu", name: "Zulu" },
];
