import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProvider from "@/components/provider-nextui";
import Footer from "@/components/Footer/footer";
import icons from "@/components/Footer/ArrayIcons";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NextUiProvider>
					{children}
					<Footer appName="Transiapp" iconItems={icons} />
				</NextUiProvider>
			</body>
		</html>
	);
}
